// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("bs-jest/lib/js/src/jest.js");

Jest.test("addition", (function () {
        return Jest.Expect[/* toBe */2](7, Jest.Expect[/* expect */0](7));
      }));

/*  Not a pure module */
