// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Aside");

function str(prim) {
  return prim;
}

function toStr(count) {
  return String(count);
}

function make(_, person) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("aside", undefined, React.createElement("p", {
                              className: "name"
                            }, person[/* name */0]), React.createElement("p", {
                              className: "messages-count"
                            }, String(person[/* messagesCount */1])), React.createElement("p", {
                              className: "followers"
                            }, String(person[/* followersCount */2])), React.createElement("p", {
                              className: "follows"
                            }, String(person[/* followsCount */3])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.str = str;
exports.toStr = toStr;
exports.make = make;
/* component Not a pure module */
