// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';


function getAvatar(name) {
  return "./imgs/" + (name + ".jpg");
}

exports.getAvatar = getAvatar;
/* No side effect */
